name: Base build & publish workflow

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      dockerfile:
        required: false
        type: string
        default: Dockerfile
      runs-on:
        required: false
        type: string
        default: self-hosted
    secrets:
      docker_username:
        required: true
      docker_access_token:
        required: true

jobs:
  publish:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_access_token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.docker_username }}/${{ inputs.image }}

      - run: docker context create tls-environment

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: 'tls-environment'

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.docker_username }}/${{ inputs.image }}:buildcache
          cache-to: type=registry,ref=${{ secrets.docker_username }}/${{ inputs.image }}:buildcache,mode=max
